version: '3'
services:
  db:
    image: postgres
    ports: 
      - "5432:5432"
    restart: always
  web:
    env_file: .env
    build: .
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ["npm", "start"]

  
